version: '2'
services:
  ssh:
    build: .
    container_name: dev
    hostname: devhost
    ports:
      - "8090:22"
    volumes:
      - ~/.oh-my-zsh:/home/dev/.oh-my-zsh
      - ~/.vim_runtime:/home/dev/.vim_runtime
      - ~/.zshrc:/home/dev/.zshrc
      - ~/.vimrc:/home/dev/.vimrc
      - ~/.tmux.conf:/home/dev/.tmux.conf
